# Generated by Django 6.0.2 on 2026-03-31 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('departement', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('type_inspection', models.CharField(default='routine', max_length=20)),
                ('type_structure', models.CharField(max_length=100)),
                ('emetteur_saisine', models.CharField(blank=True, max_length=255, null=True)),
                ('date_saisine', models.DateField(blank=True, null=True)),
                ('moyen_saisine', models.CharField(blank=True, max_length=100, null=True)),
                ('motif_saisine', models.TextField(blank=True, null=True)),
                ('observations_generales', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='BROUILLON', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('delegues', models.ManyToManyField(related_name='delegue_rapports', to=settings.AUTH_USER_MODEL)),
                ('membres_supplementaires', models.ManyToManyField(blank=True, related_name='equipe_rapports', to=settings.AUTH_USER_MODEL)),
                ('structures_inspectees', models.ManyToManyField(related_name='rapports_set', to='structures.structure')),
            ],
        ),
    ]
