# Generated by Django 6.0.2 on 2026-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('type_structure', models.CharField(choices=[('direction', 'Direction Centrale'), ('service', 'Service Déconcentré'), ('etablissement', 'Établissement Public')], max_length=50)),
                ('departement', models.CharField(max_length=100)),
                ('responsable_nom', models.CharField(max_length=255, verbose_name='Nom du responsable')),
                ('est_operationnelle', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
            },
        ),
    ]
