# Generated by Django 6.0.2 on 2026-03-31 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_remove_structure_responsable_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la structure'),
        ),
    ]
