# Generated by Django 6.0.2 on 2026-03-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('date_inspection', models.DateField()),
                ('structure', models.CharField(max_length=255)),
                ('type_rapport', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Transmis', 'Transmis'), ('Validation', 'En attente de validation')], default='Brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
