# Generated by Django 6.0.2 on 2026-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence Reco')),
                ('titre', models.CharField(max_length=255)),
                ('constat', models.TextField(verbose_name='Constat / Problème')),
                ('recommandation_detaillee', models.TextField()),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('en_cours', 'En cours'), ('soldee', 'Soldée'), ('non_realisee', 'Non réalisée')], default='brouillon', max_length=20)),
                ('date_echeance', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('rapports_lies', models.ManyToManyField(related_name='recommandations', to='core.rapport')),
                ('structures_responsables', models.ManyToManyField(related_name='recommandations_a_charger', to='structures.structure')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
